name = "pstrack-web"
main = "@tanstack/react-start/server-entry"
compatibility_date = "2025-09-02"
account_id = "e63ca873ee31a59544d22cc688fe938b"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]
