name = "pstrack"
main = "@tanstack/react-start/server-entry"
compatibility_date = "2025-09-02"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[env.development]
name = "pstrack-dev"
workers_dev = true
[env.development.vars]
NODE_ENV = "development"

[env.production]
name = "pstrack"
workers_dev = true
[env.production.vars]
NODE_ENV = "production"
