name = "pstrack"
main = "src/index.ts"
minify = true
compatibility_date = "2025-01-29"
account_id = "e63ca873ee31a59544d22cc688fe938b"

compatibility_flags = [
  "nodejs_als",
  "nodejs_compat",
  "nodejs_compat_populate_process_env",
]

# ============================================================================
# Build & bundle
# ============================================================================
keep_names = true
upload_source_maps = true
tsconfig = "tsconfig.json"

# ============================================================================
# Observability
# ============================================================================
[observability]
enabled = true
head_sampling_rate = 1
traces.enabled = true
logs.enabled = true
logs.invocation_logs = true

# ============================================================================
# BINDINGS (Cloudflare Services)
# ============================================================================
# [[kv_namespaces]]
# binding = "PSTRACK_KV"
# id = "ad5d46b117c64ca6a5a96c9f7dff284f"
